title: Jquery-gotop
description: goTop is a <2kb Scroll to Top jQuery plugin.
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

github:
  zip_url: 'https://github.com/scottdorman/jquery-gotop/zipball/master'
  tar_url: 'https://github.com/scottdorman/jquery-gotop/tarball/master'
  repository_url: 'https://github.com/scottdorman/jquery-gotop'
  
gems:
  - jekyll-mentions
